version: '3.8'

services:
  app:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./bot.db:/app/bot.db
      - ./bot.log:/app/bot.log
    environment:
      - API_PORT=8000
      - API_HOST=0.0.0.0
